# Generated by Django 3.2.13 on 2022-05-08 10:50

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20220426_2335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='%(app_label)s_%(class)s_unique__author__unique',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='%(app_label)s_%(class)s_user__neq__author',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('author', 'user'), name='posts_follow_unique__author__unique'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('author', django.db.models.expressions.F('user')), _negated=True), name='posts_follow_user__neq__author'),
        ),
    ]
