POST_CREATE_URL = '/create/'
GROUP_URL = '/group/{group_slug}/'
PROFILE_URL = '/profile/{profile_username}/'
INDEX_URL = '/'
CREATE_POST_URL = '/posts/{post_pk}/edit/'
POST_DETAIL_URL = '/posts/{post_pk}/'
FAILURE_404_URL = '/unexisting_page/'

GROUP_KWARGS = 'slug'
PROFILE_KWARGS = 'username'
POST_DETAIL_KWARGS = 'post_id'

INDEX_URL_NAME = 'posts:index'
PROFILE_URL_NAME = 'posts:profile'
GROUP_URL_NAME = 'posts:group_list'
POST_DETAIL_URL_NAME = 'posts:post_detail'
POST_EDIT_URL_NAME = 'posts:post_edit'
POST_CREATE_URL_NAME = 'posts:post_create'
FOLLOW_INDEX_URL_NAME = 'posts:follow_index'

INDEX_TEMPLATE = 'posts/index.html'
GROUP_TEMPLATE = 'posts/group_list.html'
PROFILE_TEMPLATE = 'posts/profile.html'
POST_DETAIL_TEMPLATE = 'posts/post_detail.html'
CREATE_POST_TEMPLATE = 'posts/create_post.html'
FAILURE_404_TEMPLATE = 'core/404.html'
